added rspec cases for events_controller.rb
FashioNXT/EventNXT-Fall2024 pull request #19
Opened 2024-10-12 00:15 UTC by neilgautam24-tamu

2024-10-12 01:10 UTC, XuMingSheng commented
Put all the files for testing in `spec/fixtures/files`, and change the path in your code accordingly.

2024-10-12 02:41 UTC, neilgautam24-tamu commented
@XuMingSheng I have done the mentioned changes.

2024-10-12 03:39 UTC, XuMingSheng commented
Put the file for testing in `spec/fixtures/files`.

2024-10-18 00:33 UTC, XuMingSheng commented on public/uploads/event/event_avatar/3/some-dog.jpg
Here

2024-10-18 00:33 UTC, XuMingSheng commented on public/uploads/event/event_box_office/3/Book1.xlsx
and here

2024-10-18 00:35 UTC, XuMingSheng commented on app/controllers/guests_controller.rb
remove comment of old code

2024-10-18 00:36 UTC, XuMingSheng commented on app/controllers/seats_controller.rb
remove comment of old code

2024-10-18 00:36 UTC, XuMingSheng commented on app/models/seat.rb
remove comment of old code

2024-10-18 00:37 UTC, XuMingSheng commented on spec/controllers/events_controller_spec.rb
remove comment of old code

2024-10-18 16:13 UTC, neilgautam24-tamu commented on spec/controllers/events_controller_spec.rb
Removed

2024-10-18 16:13 UTC, neilgautam24-tamu commented on app/controllers/guests_controller.rb
Removed that snippet

2024-10-18 16:29 UTC, XuMingSheng requested changes
1. Some of the comments are remained to be removed
2. Some other rspecs (besides events_controller.rb) are not passing in this PR, which are passing in dev branch. Should find the cause and modify this PR to let all rspec pass.

2024-10-18 16:29 UTC, XuMingSheng commented on spec/controllers/events_controller_spec.rb
Some of them are still there.

2024-10-18 16:29 UTC, XuMingSheng commented on spec/controllers/events_controller_spec.rb
> +  # describe "GET #index" do
here

2024-10-18 16:29 UTC, XuMingSheng commented on spec/controllers/events_controller_spec.rb
> +  # describe "GET #show" do
here

2024-10-18 16:29 UTC, XuMingSheng commented on app/models/seat.rb
Some of them are still there.

2024-10-18 16:29 UTC, XuMingSheng commented on app/models/seat.rb
> +# class Seat < ApplicationRecord
Here

2024-10-25 04:02 UTC, XuMingSheng commented on features/manage_seat_level.feature
> +Scenario: Edit event details
Why is this scenario be here? Shouldn't it be in a separate feature such as `events.feature`?

2024-10-26 01:17 UTC, XuMingSheng approved these changes

2024-10-26 01:18 UTC, merged